### ISSUE TITLE
Some enhancement

### ISSUE THREAD

**Issue by halybang** [hexya-erp/hexya#11]
-Support JSON data type as PostgreSQL (native support),
-Support PostgreSQL extensions (I want to use some extensions like timeseridb ...)
-Modules Pre_Init function:
Some modules need to setup some params before hexya start, but after read configuration.
If module call setup code inside module-init functions, it can not read/parse config. If call in module-Post_Init function, the server already started, so modules can not register new route (for gin).
For exam: I want to register an OAuth handler (http://host:post/auth/:provider), using params(path/ClientID/SecrectID) from config file.

**Comment by npiganeau** [comment]
Pre_Init : I agree. I add it to my soon-to-do list.

Postgres refinements: not my priority for the moment as this is not required to port Odoo modules, but I'll be glad to review a PR on the subject.

**Comment by npiganeau** [comment]
PreInit fonctions has just been implemented.
