### ISSUE TITLE
Underlying called using nil *Condition pointer 

### ISSUE THREAD

**Issue by halybang** [hexya-erp/hexya#12]
Can not change user's company:
Steps:
1. Create company A
2. Create new user, try to set 'Current Company' to company A. A popup warning appears:

>value method github.com/hexya-erp/hexya/hexya/models.Condition.Underlying called using nil *Condition pointer

We can't write/update record.

**Comment by npiganeau** [comment]
Fixed by https://github.com/hexya-erp/hexya-base/commit/67a816fc264af88cef56939d0dbac4ba1cbec402
