### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by blaggacao** [hexya-erp/hexya#122]
https://github.com/hexya-erp/hexya/blob/86eeb57a7a94211bc474ed8a49dcb8b962189b9d/cmd/server.go#L36

**Comment by npiganeau** [comment]
I'm not sure to understand why using viper is so nice, but I'm glad you like it !

**Comment by blaggacao** [comment]
I like it because it has a **proper** config interface with multiple backends. This makes ConfigManagement concerns a little easier and more flexible during deployment workflows.

This has been pain point over at the upstream inspiration project.

I haven't had the chance to play with hydra, yet. Just skimmed over the code. I also like you did choose *not* to replicate the multi-db registry nonsense.

Maybe looking further, I find a few other easter eggs. :wink:
