### ISSUE TITLE
Could it run a module along as a server?

### ISSUE THREAD

**Issue by hzmnet** [hexya-erp/hexya#17]
Could it run a module along as a server?

**Comment by npiganeau** [comment]
Hi, 

Thanks for your interest in Hexya. Modules are really much like in Odoo. Each module adds business features to Hexya and (potentially) depend on other modules. The hexya core itself has no business feature at all, everything is implemented as a module.

So if you want to start a single module, you just need to start Hexya with the only module you want in the "Modules" list of the config file (see http://hexya.io/docs/install/).

**Comment by hzmnet** [comment]
sorry! My meaning is distributed,  every module as a service running on difference computer!

**Comment by npiganeau** [comment]
Ok, I understand the question.

No, Hexya is not a microservice framework. It is a monolithic yet modular framework to build complex business applications such as an ERP very quickly by a very high level of abstraction. Its modular design is especially useful to be able to adapt the features to specific company needs while still being able to reuse code at much as possible.

Scalability of Hexya applications is mainly foreseen through the setup of several Hexya servers (each with the whole app) connected to a distributed CockroachDB.
