### ISSUE TITLE
Config file was not read correctly.

### ISSUE THREAD

**Issue by halybang** [hexya-erp/hexya#2]
Run `hexya -c config_file_name` not work.
Reason: Corbra parses command line args when call Execute() method.
How to fix:
Modify `cmd/hexya.go`
1. In func init(), add `cobra.OnInitialize(initConfig)`
2. Add function
```golang
func initConfig() {
	cfgFile := viper.GetString("ConfigFileName")
	// Read config either from cfgFile or from home directory!
	viper.AddConfigPath("/etc/hexya/")
	viper.AddConfigPath("$HOME/.hexya")
	viper.AddConfigPath(".")
	if cfgFile == "" {
		cfgFile = "hexya"
	}
	viper.SetConfigFile(cfgFile)
	viper.ReadInConfig()
}
```

**Comment by npiganeau** [comment]
You're right, this wasn't implemented.

Can you open a PR with your proposal ?
