### ISSUE TITLE
Generate error, pool killed

### ISSUE THREAD

**Issue by labneco** [hexya-erp/hexya#29]
I try install the hexya on ubuntu vps. The hexya command "hexya generate" returns a error:

Generating pool...Killed

Someone know why this error show up and the hexya don't complete the generating process?

**Comment by npiganeau** [comment]
Can you send the complete output of `hexya generate` as well as your config file ?

**Comment by labneco** [comment]
root@labneco:~/go/src/github.com/hexya-erp/hexya-demo# ../hexya/main generate 
Hexya Generate
--------------
Detected Hexya root directory at /root/go/src/github.com/hexya-erp/hexya.
Modules paths:
 - github.com/hexya-erp/hexya-addons/sale
Loading program...Ok
Generating symlinks...Ok
Generating pool...Killed

**Comment by labneco** [comment]
Work, and another error
I don't know what I did, but pass from the generating pool and stop on next step:
Checking the generated code...Killed

**Comment by npiganeau** [comment]
What are the specs of your VPS ? Hexya needs an awful lot of memory to generate and compile (>8GB). Can you check if you are not running out of memory ?

**Comment by labneco** [comment]
I thing the problem is the memory, on my laptop a have just 4gb. That's the problem?
