### ISSUE TITLE
Support multi-databases as Odoo (for SaaS)

### ISSUE THREAD

**Issue by halybang** [hexya-erp/hexya#5]
So, we can create SaaS service with fix pre-installed addons.

**Comment by npiganeau** [comment]
Honestly I don't believe in SaaS with fixed addons. The ERP business is all about customization, so I believe each customer will have its own Hexya with its own addons.

If we were to build a SaaS service for Hexya, it would still be possible by building and launching on the fly an instance for each customer on a different port, all behind a reverse proxy.

So I don't intend to support multi-database at all.
